### ISSUE TITLE
What to do for single circle with single icon?

### ISSUE THREAD

**Issue by ghost** [Ezaldeen99/flutter_circular_animator#2]
Can this widget be customized to use only one circle instead of two?
Also, only one icon on the circle instead of the 2-3 icons that are present in the rings?

**Comment by Ezaldeen99** [comment]
This is a good suggestion actually, I will start making this widget more customizable

**Comment by Ezaldeen99** [comment]
I uploaded a version that supports only one ring today, the icons update will be published soon
